package application.domain.models;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import application.domain.exceptions.InsufficientStockException;
import application.domain.valueobjects.InventoryMovementType;

/**
 * Inventory - Domain Model.
 *
 * Represents the available stock of a physical product at a specific
 * warehouse. Inventory is distributed and must be mandatorily linked to a
 * product and a warehouse.
 *
 * Business rules:
 * - Negative stock levels shall never be allowed under any circumstances.
 * - Inventory that does not exist or is marked as damaged cannot be
 *   reserved.
 *
 * Relationships:
 * - An Inventory references one PhysicalProduct and one Warehouse.
 * - An Inventory generates zero or more InventoryMovement instances.
 */
public class Inventory {

    private final PhysicalProduct product;
    private final Warehouse warehouse;
    private int availableQuantity;
    private int reservedQuantity;
    private boolean damaged;
    private final List<InventoryMovement> movements;

    public Inventory(PhysicalProduct product, Warehouse warehouse,
                     int initialQuantity) {
        if (product == null) {
            throw new IllegalArgumentException("Inventory product must not be null");
        }
        if (warehouse == null) {
            throw new IllegalArgumentException("Inventory warehouse must not be null");
        }
        if (initialQuantity < 0) {
            throw new IllegalArgumentException("Initial quantity must not be negative");
        }
        this.product = product;
        this.warehouse = warehouse;
        this.availableQuantity = initialQuantity;
        this.reservedQuantity = 0;
        this.damaged = false;
        this.movements = new ArrayList<>();
        warehouse.attachInventory(this);
    }

    /** Product the stock record corresponds to. */
    public PhysicalProduct getProduct() {
        return product;
    }

    /** Warehouse where the stock is held. */
    public Warehouse getWarehouse() {
        return warehouse;
    }

    /** Units available for sale. */
    public int getAvailableQuantity() {
        return availableQuantity;
    }

    /** Units reserved by orders in progress. */
    public int getReservedQuantity() {
        return reservedQuantity;
    }

    /** Damaged inventory cannot be reserved. */
    public boolean isDamaged() {
        return damaged;
    }

    public void markAsDamaged() {
        this.damaged = true;
    }

    public void markAsOperational() {
        this.damaged = false;
    }

    /** Movements generated by this inventory. Read-only view. */
    public List<InventoryMovement> getMovements() {
        return Collections.unmodifiableList(movements);
    }

    void attachMovement(InventoryMovement movement) {
        movements.add(movement);
    }

    /**
     * Registers new stock into the warehouse (INGRESO).
     */
    public void stockIn(int quantity) {
        if (quantity <= 0) {
            throw new IllegalArgumentException("Stock-in quantity must be positive");
        }
        availableQuantity += quantity;
        recordMovement(InventoryMovementType.INGRESO, quantity);
    }

    /**
     * Sets aside stock for an order in progress (RESERVA).
     *
     * Business rule: negative stock is never allowed; damaged or missing
     * inventory cannot be reserved.
     */
    public void reserve(int quantity) {
        if (quantity <= 0) {
            throw new IllegalArgumentException("Reservation quantity must be positive");
        }
        if (damaged) {
            throw new InsufficientStockException(
                    "Damaged inventory cannot be reserved for product "
                            + product.getIdentifier());
        }
        if (!warehouse.isOperational()) {
            throw new InsufficientStockException(
                    "Inactive warehouse cannot reserve stock for product "
                            + product.getIdentifier());
        }
        if (availableQuantity < quantity) {
            throw new InsufficientStockException(
                    "Insufficient stock for product " + product.getIdentifier()
                            + ": requested=" + quantity
                            + ", available=" + availableQuantity);
        }
        availableQuantity -= quantity;
        reservedQuantity += quantity;
        recordMovement(InventoryMovementType.RESERVA, quantity);
    }

    /**
     * Decreases reserved stock due to an order dispatch (SALIDA_POR_VENTA).
     */
    public void releaseSaleOutflow(int quantity) {
        if (quantity <= 0) {
            throw new IllegalArgumentException("Outflow quantity must be positive");
        }
        if (reservedQuantity < quantity) {
            throw new IllegalStateException(
                    "Cannot outflow more than the reserved quantity for product "
                            + product.getIdentifier());
        }
        reservedQuantity -= quantity;
        recordMovement(InventoryMovementType.SALIDA_POR_VENTA, quantity);
    }

    /**
     * Manual correction of stock (AJUSTE). The resulting stock can never be
     * negative.
     */
    public void adjust(int delta) {
        if (availableQuantity + delta < 0) {
            throw new IllegalArgumentException(
                    "Adjustment would produce negative stock, which is never allowed");
        }
        availableQuantity += delta;
        recordMovement(InventoryMovementType.AJUSTE, Math.abs(delta));
    }

    /**
     * Stock re-entry due to an approved return (DEVOLUCION).
     */
    public void returnStock(int quantity) {
        if (quantity <= 0) {
            throw new IllegalArgumentException("Return quantity must be positive");
        }
        availableQuantity += quantity;
        recordMovement(InventoryMovementType.DEVOLUCION, quantity);
    }

    private void recordMovement(InventoryMovementType type, int quantity) {
        new InventoryMovement(type, quantity, this);
    }
}