package application.domain.models;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.concurrent.atomic.AtomicLong;

import application.domain.valueobjects.Currency;

/**
 * Invoice - Domain Model.
 *
 * Represents the commercial information associated with the sale of an
 * order.
 *
 * Relationships:
 * - An Invoice is generated from one Order.
 */
public class Invoice {

    private static final AtomicLong SEQUENCE = new AtomicLong(50000);

    private final String invoiceId;
    private final Order order;
    private final LocalDateTime issueDate;
    private final BigDecimal totalAmount;
    private final Currency currency;

    /** Generated by the domain when payment of the order is confirmed. */
    Invoice(Order order) {
        this.invoiceId = "INV-" + SEQUENCE.incrementAndGet();
        this.order = order;
        this.issueDate = LocalDateTime.now();
        this.totalAmount = order.getTotalAmount();
        this.currency = Currency.COP;
    }

    /** Reconstitution constructor (persistence). */
    public Invoice(String invoiceId, Order order, LocalDateTime issueDate,
                   BigDecimal totalAmount, Currency currency) {
        this.invoiceId = invoiceId;
        this.order = order;
        this.issueDate = issueDate;
        this.totalAmount = totalAmount;
        this.currency = currency;
        order.attachInvoice(this);
    }

    /** Unique invoice identifier. */
    public String getInvoiceId() {
        return invoiceId;
    }

    /** Invoiced order. */
    public Order getOrder() {
        return order;
    }

    /** Date and time the invoice was issued. */
    public LocalDateTime getIssueDate() {
        return issueDate;
    }

    /** Total invoiced value. */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /** Currency in which the invoice is issued. */
    public Currency getCurrency() {
        return currency;
    }
}