package application.domain.models;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.concurrent.atomic.AtomicLong;

import application.domain.valueobjects.Currency;
import application.domain.valueobjects.InvoiceStatus;

/**
 * Invoice - Domain Model.
 *
 * Represents the commercial information associated with the sale of an
 * order.
 *
 * Relationships:
 * - An Invoice is generated from one Order.
 */
public class Invoice {

    private static final AtomicLong SEQUENCE = new AtomicLong(50000);

    private final String invoiceId;
    private final Order order;
    private final LocalDateTime issueDate;
    private final BigDecimal totalAmount;
    private final Currency currency;
    private InvoiceStatus status;

    /** Generated by the domain when payment of the order is confirmed. */
    public Invoice(Order order) {
        this.invoiceId = "INV-" + SEQUENCE.incrementAndGet();
        this.order = order;
        this.issueDate = LocalDateTime.now();
        this.totalAmount = order.getTotalAmount();
        this.currency = Currency.COP;
        this.status = InvoiceStatus.EMITIDA;
        // Every invoice created from an order registers itself on that order,
        // so the order and its invoice can never diverge.
        order.attachInvoice(this);
    }

    /** Reconstitution constructor (persistence). */
    public Invoice(String invoiceId, Order order, LocalDateTime issueDate,
                   BigDecimal totalAmount, Currency currency) {
        this(invoiceId, order, issueDate, totalAmount, currency,
                InvoiceStatus.EMITIDA);
    }

    /** Reconstitution constructor with explicit status (persistence). */
    public Invoice(String invoiceId, Order order, LocalDateTime issueDate,
                   BigDecimal totalAmount, Currency currency,
                   InvoiceStatus status) {
        this.invoiceId = invoiceId;
        this.order = order;
        this.issueDate = issueDate;
        this.totalAmount = totalAmount;
        this.currency = currency;
        this.status = status;
        order.attachInvoice(this);
    }

    /** Unique invoice identifier. */
    public String getInvoiceId() {
        return invoiceId;
    }

    /** Invoiced order. */
    public Order getOrder() {
        return order;
    }

    /** Date and time the invoice was issued. */
    public LocalDateTime getIssueDate() {
        return issueDate;
    }

    /** Total invoiced value. */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /** Currency in which the invoice is issued. */
    public Currency getCurrency() {
        return currency;
    }
/** Current commercial status of the invoice. */
    public InvoiceStatus getStatus() {
        return status;
    }

    /** True when the invoice has been cancelled. */
    public boolean isVoid() {
        return InvoiceStatus.ANULADA.equals(status);
    }

    /** EMITIDA -> ANULADA. Cancels a previously generated invoice. */
    public void voidInvoice() {
        ensureStatus(InvoiceStatus.EMITIDA, "Only issued invoices can be voided");
        this.status = InvoiceStatus.ANULADA;
    }

    private void ensureStatus(InvoiceStatus expected, String message) {
        if (!expected.equals(status)) {
            throw new IllegalStateException(message + " (current status: "
                    + status.getCode() + ")");
        }
    }
}