package application.domain.models;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import application.domain.exceptions.InvalidReturnRequestException;
import application.domain.exceptions.OrderAlreadyCompletedException;
import application.domain.valueobjects.OrderStatus;

/**
 * Order - Domain Model.
 *
 * Represents the formal commercial commitment between a buyer and one or
 * more sellers. Its lifecycle is the central process of the system.
 *
 * Lifecycle: CART -> PENDING_PAYMENT -> PAID -> DISPATCHED
 *            -> DELIVERED_COMPLETED.
 *
 * Business rule:
 * - A completed order shall not be modified under any circumstances.
 *
 * Relationships:
 * - An Order is placed by one Buyer.
 * - An Order contains one or more OrderItem instances.
 * - An Order generates one Invoice.
 * - An Order may generate one Shipment when it includes physical products.
 * - An Order may generate zero or more Return instances.
 */
public class Order {

    private static final AtomicInteger SEQUENCE = new AtomicInteger(1000);

    private final Integer orderId;
    private final Buyer buyer;
    private final List<OrderItem> items;
    private OrderStatus orderStatus;
    private final LocalDateTime creationDate;
    private LocalDateTime paymentConfirmationDate;
    private String deliveryAddress;
    private Invoice invoice;
    private Shipment shipment;
    private final List<Return> returns;

    /**
     * Creates an order from a confirmed shopping cart. The initial status
     * is PENDING_PAYMENT (cart conversion step of the lifecycle).
     */
    public Order(Buyer buyer, ShoppingCart cart, String deliveryAddress) {
        this(SEQUENCE.incrementAndGet(), buyer, deliveryAddress);
        if (cart == null || cart.getItems().isEmpty()) {
            throw new IllegalArgumentException(
                    "An order requires at least one item from the cart");
        }
        for (CartItem cartItem : cart.getItems()) {
            items.add(new OrderItem(cartItem.getProduct(), cartItem.getQuantity()));
        }
        buyer.attachOrder(this);
    }

    /** Reconstitution constructor (persistence). */
    public Order(Integer orderId, Buyer buyer, String deliveryAddress) {
        if (buyer == null) {
            throw new IllegalArgumentException("Order buyer must not be null");
        }
        if (deliveryAddress == null || deliveryAddress.isBlank()) {
            throw new IllegalArgumentException("Order delivery address must not be null or blank");
        }
        this.orderId = orderId;
        this.buyer = buyer;
        this.items = new ArrayList<>();
        this.orderStatus = OrderStatus.PENDIENTE_DE_PAGO;
        this.creationDate = LocalDateTime.now();
        this.deliveryAddress = deliveryAddress;
        this.returns = new ArrayList<>();
    }

    /** Unique order identifier. */
    public Integer getOrderId() {
        return orderId;
    }

    /** Buyer who places the order. */
    public Buyer getBuyer() {
        return buyer;
    }

    /** Confirmed products and quantities. Read-only view. */
    public List<OrderItem> getItems() {
        return Collections.unmodifiableList(items);
    }

    void attachItem(OrderItem item) {
        items.add(item);
    }

    /** Current state of the order's lifecycle. */
    public OrderStatus getOrderStatus() {
        return orderStatus;
    }

    /** Date and time the order was created. */
    public LocalDateTime getCreationDate() {
        return creationDate;
    }

    /** Date on which payment was confirmed. */
    public LocalDateTime getPaymentConfirmationDate() {
        return paymentConfirmationDate;
    }

    /** Delivery address selected by the buyer. */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    public void setDeliveryAddress(String deliveryAddress) {
        ensureModifiable();
        this.deliveryAddress = deliveryAddress;
    }

    /** The invoice generated by this order, if any. */
    public Invoice getInvoice() {
        return invoice;
    }

    void attachInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    /** The shipment generated by this order, if any. */
    public Shipment getShipment() {
        return shipment;
    }

    void attachShipment(Shipment shipment) {
        this.shipment = shipment;
    }

    /** Returns requested against this order. Read-only view. */
    public List<Return> getReturns() {
        return Collections.unmodifiableList(returns);
    }

    void attachReturn(Return returnRequest) {
        returns.add(returnRequest);
    }

    /**
     * Confirms payment: PENDING_PAYMENT -> PAID. Preparation processes
     * begin; the invoice is issued at this point.
     */
    public Invoice confirmPayment() {
        ensureStatus(OrderStatus.PENDIENTE_DE_PAGO,
                "Payment can only be confirmed for an order pending payment");
        this.orderStatus = OrderStatus.PAGADO;
        this.paymentConfirmationDate = LocalDateTime.now();
        this.invoice = new Invoice(this);
        return invoice;
    }

    /**
     * Marks the order as dispatched after its shipment leaves the
     * warehouse: PAID -> DISPATCHED.
     */
    public void markDispatched() {
        ensureStatus(OrderStatus.PAGADO,
                "Only paid orders can be dispatched");
        this.orderStatus = OrderStatus.DESPACHADO;
    }

    /**
     * Marks successful delivery conclusion: DISPATCHED ->
     * DELIVERED_COMPLETED. From this point the order is immutable.
     */
    public void markDelivered() {
        ensureStatus(OrderStatus.DESPACHADO,
                "Only dispatched orders can be delivered");
        this.orderStatus = OrderStatus.ENTREGADO_FINALIZADO;
    }

    /**
     * Requests a return. Only completed orders belonging to the requesting
     * buyer accept returns.
     */
    public Return requestReturn(String returnId, ReturnReasonHolder reason) {
        if (!OrderStatus.ENTREGADO_FINALIZADO.equals(orderStatus)) {
            throw new InvalidReturnRequestException(
                    "Returns can only be requested for delivered/completed orders");
        }
        Return returnRequest = new Return(returnId, this, reason.reason());
        returns.add(returnRequest);
        return returnRequest;
    }

    /** Total value of the order. */
    public BigDecimal getTotalAmount() {
        return items.stream()
                .map(OrderItem::getLineTotal)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /** True when the order reached its final state. */
    public boolean isCompleted() {
        return OrderStatus.ENTREGADO_FINALIZADO.equals(orderStatus);
    }

    /** True when the order includes at least one physical product. */
    public boolean containsPhysicalProducts() {
        return items.stream().anyMatch(item ->
                item.getProduct() instanceof PhysicalProduct);
    }

    /** Guards mutations once the order is completed. */
    private void ensureModifiable() {
        if (isCompleted()) {
            throw new OrderAlreadyCompletedException(
                    "Order " + orderId + " is completed and shall not be modified");
        }
    }

    private void ensureStatus(OrderStatus expected, String message) {
        if (!expected.equals(orderStatus)) {
            throw new IllegalStateException(message + " (current status: "
                    + orderStatus.getCode() + ")");
        }
    }

    /** Simple carrier for the primitive enum ReturnReason. */
    public record ReturnReasonHolder(application.domain.enums.ReturnReason reason) {
    }
}