package application.domain.models;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.concurrent.atomic.AtomicLong;

import application.domain.valueobjects.RefundStatus;

/**
 * Refund - Domain Model.
 *
 * Represents the monetary refund originated by an approved return.
 *
 * Lifecycle: PENDIENTE -> PROCESADO | RECHAZADO.
 *
 * Relationships:
 * - A Refund is generated from one approved Return.
 */
public class Refund {

    private static final AtomicLong SEQUENCE = new AtomicLong(80000);

    private final String refundId;
    private final Return returnRequest;
    private final BigDecimal refundedAmount;
    private RefundStatus refundStatus;
    private LocalDateTime processingDate;

    /** Generated by the domain when the return is approved. */
    Refund(Return returnRequest) {
        this.refundId = "RFD-" + SEQUENCE.incrementAndGet();
        this.returnRequest = returnRequest;
        this.refundedAmount = returnRequest.getOrder().getTotalAmount();
        this.refundStatus = RefundStatus.PENDIENTE;
        returnRequest.attachRefund(this);
    }

    /** Reconstitution constructor (persistence). */
    public Refund(String refundId, Return returnRequest,
                  BigDecimal refundedAmount, RefundStatus refundStatus,
                  LocalDateTime processingDate) {
        this.refundId = refundId;
        this.returnRequest = returnRequest;
        this.refundedAmount = refundedAmount;
        this.refundStatus = refundStatus;
        this.processingDate = processingDate;
        returnRequest.attachRefund(this);
    }

    /** Unique refund identifier. */
    public String getRefundId() {
        return refundId;
    }

    /** Return that originated the refund. */
    public Return getReturnRequest() {
        return returnRequest;
    }

    /** Value refunded to the buyer. */
    public BigDecimal getRefundedAmount() {
        return refundedAmount;
    }

    /** Current status of the refund. */
    public RefundStatus getRefundStatus() {
        return refundStatus;
    }

    /** Date and time the refund was processed. */
    public LocalDateTime getProcessingDate() {
        return processingDate;
    }

    /** PENDIENTE -> PROCESADO. */
    public void markProcessed() {
        ensureStatus(RefundStatus.PENDIENTE, "Only pending refunds can be processed");
        this.refundStatus = RefundStatus.PROCESADO;
        this.processingDate = LocalDateTime.now();
    }

    /** PENDIENTE -> RECHAZADO. */
    public void reject() {
        ensureStatus(RefundStatus.PENDIENTE, "Only pending refunds can be rejected");
        this.refundStatus = RefundStatus.RECHAZADO;
    }

    private void ensureStatus(RefundStatus expected, String message) {
        if (!expected.equals(refundStatus)) {
            throw new IllegalStateException(message + " (current status: "
                    + refundStatus.getCode() + ")");
        }
    }
}