package application.domain.models;

import java.time.LocalDateTime;
import java.util.concurrent.atomic.AtomicLong;

import application.domain.enums.ApprovalDecision;
import application.domain.enums.ReturnReason;
import application.domain.valueobjects.ReturnStatus;

/**
 * Return - Domain Model.
 *
 * Represents a request to return one or more products from an order that
 * has already been delivered.
 *
 * Lifecycle: SOLICITADA -> EN_REVISION -> APROBADA | RECHAZADA.
 *
 * Relationships:
 * - A Return is associated with one Order.
 * - A Return may generate one Refund when approved.
 */
public class Return {

    private static final AtomicLong SEQUENCE = new AtomicLong(70000);

    private final String returnId;
    private final Order order;
    private final ReturnReason reason;
    private ReturnStatus returnStatus;
    private final LocalDateTime requestDate;
    private ApprovalDecision decision;
    private Refund refund;

    /** Created by the domain when the buyer requests the return. */
    public Return(String returnId, Order order, ReturnReason reason) {
        if (order == null) {
            throw new IllegalArgumentException("Return order must not be null");
        }
        if (reason == null) {
            throw new IllegalArgumentException("Return reason must not be null");
        }
        this.returnId = returnId != null ? returnId : "RET-" + SEQUENCE.incrementAndGet();
        this.order = order;
        this.reason = reason;
        this.returnStatus = ReturnStatus.SOLICITADA;
        this.requestDate = LocalDateTime.now();
        order.attachReturn(this);
    }

    /** Unique return identifier. */
    public String getReturnId() {
        return returnId;
    }

    /** Order the return request applies to. */
    public Order getOrder() {
        return order;
    }

    /** Declared reason for the return. */
    public ReturnReason getReason() {
        return reason;
    }

    /** Current status of the request. */
    public ReturnStatus getReturnStatus() {
        return returnStatus;
    }

    /** Date and time the return was requested. */
    public LocalDateTime getRequestDate() {
        return requestDate;
    }

    /** Outcome of the request's evaluation. */
    public ApprovalDecision getDecision() {
        return decision;
    }

    /** The refund generated by this return, if approved and processed. */
    public Refund getRefund() {
        return refund;
    }

    void attachRefund(Refund refund) {
        this.refund = refund;
    }

    /** SOLICITADA -> EN_REVISION. */
    public void markUnderReview() {
        ensureStatus(ReturnStatus.SOLICITADA, "Only requested returns can move to review");
        this.returnStatus = ReturnStatus.EN_REVISION;
    }

    /**
     * EN_REVISION -> APROBADA with an approval decision. An approved return
     * enables the generation of a Refund.
     */
    public Refund approve() {
        ensureStatus(ReturnStatus.EN_REVISION, "Only returns under review can be approved");
        this.decision = ApprovalDecision.APROBADO;
        this.returnStatus = ReturnStatus.APROBADA;
        this.refund = new Refund(this);
        return refund;
    }

    /** EN_REVISION -> RECHAZADA with a rejection decision. */
    public void reject() {
        ensureStatus(ReturnStatus.EN_REVISION, "Only returns under review can be rejected");
        this.decision = ApprovalDecision.RECHAZADO;
        this.returnStatus = ReturnStatus.RECHAZADA;
    }

    private void ensureStatus(ReturnStatus expected, String message) {
        if (!expected.equals(returnStatus)) {
            throw new IllegalStateException(message + " (current status: "
                    + returnStatus.getCode() + ")");
        }
    }
}